from pathlib import Path
import json

BASE_DIR = Path(__file__).resolve().parent.parent
CAREERS_FILE = BASE_DIR / "data" / "career_requirements.json"
TOP_CAREERS_FILE = "../data/top_career_matches.json"
OUTPUT_FILE = "../data/career_comparison.json"


# ============================================================
# LOAD CAREER REQUIREMENTS
# ============================================================

def load_career_requirements():
    """
    Load all career requirements from JSON.
    """

    with open(
        CAREERS_FILE,
        "r",
        encoding="utf-8"
    ) as file:
        data = json.load(file)

    return data["careers"]


# ============================================================
# LOAD TOP CAREER MATCHES
# ============================================================

def load_top_careers():
    """
    Load top career matches generated by 4.3.
    """

    with open(
        TOP_CAREERS_FILE,
        "r",
        encoding="utf-8"
    ) as file:
        data = json.load(file)

    return data["top_careers"]


# ============================================================
# FIND CAREER DETAILS
# ============================================================

def get_career_details(career_name, careers):
    """
    Find complete career information by career name.
    """

    for career in careers:

        if career["career"] == career_name:
            return career

    return None


# ============================================================
# COMPARE CAREERS
# ============================================================

def compare_careers(selected_careers, student_skills):
    """
    Compare multiple careers using:
    - Match percentage
    - Required skills
    - Matching skills
    - Skill gaps
    - Career description
    """

    careers = load_career_requirements()

    comparison = []

    for selected in selected_careers:

        career_name = selected["career"]
        match_percentage = selected["match_percentage"]

        career = get_career_details(
            career_name,
            careers
        )

        if career is None:
            continue

        required_skills = career.get(
            "required_skills",
            {}
        )

        matching_skills = []
        skill_gaps = []

        for skill, required_level in required_skills.items():

            student_level = student_skills.get(
                skill,
                0
            )

            if student_level >= required_level:
                matching_skills.append(skill)

            else:
                skill_gaps.append({
                    "skill": skill,
                    "current": student_level,
                    "required": required_level
                })

        comparison.append({

            "career": career_name,

            "match_percentage": match_percentage,

            "description": career.get(
                "description",
                ""
            ),

            "required_skills": required_skills,

            "matching_skills": matching_skills,

            "skill_gaps": skill_gaps

        })

    return comparison


# ============================================================
# GENERATE COMPARISON RESULT
# ============================================================

def generate_comparison_result(
    selected_careers,
    student_skills
):
    """
    Generate final career comparison result.
    """

    comparison = compare_careers(
        selected_careers,
        student_skills
    )

    return {

        "comparison": {

            "careers_compared": len(
                comparison
            ),

            "careers": comparison

        }

    }


# ============================================================
# SAVE RESULT
# ============================================================

def save_comparison_result(result):
    """
    Save career comparison result as JSON.
    """

    with open(
        OUTPUT_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            result,
            file,
            indent=2,
            ensure_ascii=False
        )

    print(
        f"\nComparison result saved: "
        f"{OUTPUT_FILE}"
    )


# ============================================================
# MAIN TEST
# ============================================================

if __name__ == "__main__":

    print("\n========================================")
    print("MINERVA CAREER COMPARISON TEST")
    print("========================================")

    # --------------------------------------------------------
    # Load top career matches
    # --------------------------------------------------------

    top_careers = load_top_careers()

    # Compare top 3 careers
    selected_careers = top_careers[:3]

    # --------------------------------------------------------
    # Sample student skill profile
    # --------------------------------------------------------

    sample_student_skills = {

        "problem_solving": 85,

        "analytical_thinking": 82,

        "logical_reasoning": 80,

        "technical_aptitude": 78,

        "creativity": 65,

        "communication": 60,

        "attention_to_detail": 70,

        "learning_ability": 88

    }

    # --------------------------------------------------------
    # Generate comparison
    # --------------------------------------------------------

    final_result = generate_comparison_result(
        selected_careers,
        sample_student_skills
    )

    # --------------------------------------------------------
    # Display comparison
    # --------------------------------------------------------

    print("\nCareers Compared:")
    print("----------------------------------------")

    for index, career in enumerate(
        final_result["comparison"]["careers"],
        start=1
    ):

        print(
            f"{index}. "
            f"{career['career']} "
            f"→ "
            f"{career['match_percentage']}%"
        )

        print(
            f"   Description: "
            f"{career['description']}"
        )

        print(
            "   Matching Skills: "
            + (
                ", ".join(
                    career["matching_skills"]
                )
                if career["matching_skills"]
                else "None"
            )
        )

        print("   Skill Gaps:")

        if career["skill_gaps"]:

            for gap in career["skill_gaps"]:

                print(
                    f"      - {gap['skill']}: "
                    f"{gap['current']} / "
                    f"{gap['required']}"
                )

        else:

            print("      None")

        print()

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    save_comparison_result(
        final_result
    )