"""
Minerva Career Intelligence
4.4 — Career Recommendation

Purpose:
    Combine:
    - Student skill profile
    - Career requirements
    - Career matching results

    to generate:
    - Matching skills
    - Skill gaps
    - Why this career?
    - Final career recommendations
"""

import json
import os


# ============================================================
# CONFIGURATION
# ============================================================

CAREERS_FILE = "../data/career_requirements.json"
TOP_CAREERS_FILE = "../data/top_career_matches.json"
OUTPUT_FILE = "../data/career_recommendations.json"


# ============================================================
# LOAD CAREER REQUIREMENTS
# ============================================================

def load_career_requirements():
    """
    Load career requirements from JSON.
    """

    with open(
        CAREERS_FILE,
        "r",
        encoding="utf-8"
    ) as file:

        data = json.load(file)

    # Support both possible JSON structures
    if isinstance(data, dict):

        if "careers" in data:
            return data["careers"]

        return data

    return data


# ============================================================
# LOAD TOP CAREERS
# ============================================================

def load_top_careers():
    """
    Load Top Career Matches generated by 4.3.
    """

    with open(
        TOP_CAREERS_FILE,
        "r",
        encoding="utf-8"
    ) as file:

        data = json.load(file)

    return data.get("top_careers", [])


# ============================================================
# NORMALIZE CAREER REQUIREMENTS
# ============================================================

def normalize_requirements(career):
    """
    Extract required skills from different possible
    career dataset formats.
    """

    required_skills = (
        career.get("required_skills")
        or career.get("skills")
        or career.get("requirements")
        or []
    )

    if isinstance(required_skills, dict):

        required_skills = list(
            required_skills.keys()
        )

    return [
        str(skill).strip().lower()
        for skill in required_skills
    ]


# ============================================================
# FIND CAREER
# ============================================================

def find_career_requirements(
    career_name,
    careers
):
    """
    Find career requirement information
    using the career name.
    """

    target = career_name.strip().lower()

    for career in careers:

        name = (
            career.get("career")
            or career.get("career_name")
            or career.get("name")
            or ""
        )

        if name.strip().lower() == target:
            return career

    return None


# ============================================================
# FIND MATCHING SKILLS
# ============================================================

def find_matching_skills(
    student_skills,
    required_skills
):
    """
    Identify skills that exist in both
    student profile and career requirements.
    """

    student_skill_names = {
        str(skill).strip().lower()
        for skill in student_skills
    }

    matching = []

    for skill in required_skills:

        if skill in student_skill_names:
            matching.append(skill)

    return matching


# ============================================================
# FIND SKILL GAPS
# ============================================================

def find_skill_gaps(
    student_skills,
    required_skills
):
    """
    Identify career skills that are missing
    from the student's skill profile.
    """

    student_skill_names = {
        str(skill).strip().lower()
        for skill in student_skills
    }

    gaps = []

    for skill in required_skills:

        if skill not in student_skill_names:
            gaps.append(skill)

    return gaps


# ============================================================
# GENERATE WHY THIS CAREER
# ============================================================

def generate_why_career(
    career,
    percentage,
    matching_skills,
    skill_gaps
):
    """
    Generate a meaningful explanation
    for the career recommendation.
    """

    if percentage >= 90:
        match_level = "excellent"
    elif percentage >= 80:
        match_level = "strong"
    elif percentage >= 70:
        match_level = "good"
    elif percentage >= 60:
        match_level = "moderate"
    else:
        match_level = "developing"

    if matching_skills:

        skill_text = ", ".join(
            skill.replace("_", " ")
            for skill in matching_skills[:5]
        )

        explanation = (
            f"{career} is a {match_level} career match "
            f"with a {percentage}% compatibility score. "
            f"Your profile aligns with skills such as "
            f"{skill_text}."
        )

    else:

        explanation = (
            f"{career} has a {match_level} career match "
            f"with a {percentage}% compatibility score "
            f"based on your assessment profile."
        )

    if skill_gaps:

        gap_text = ", ".join(
            skill.replace("_", " ")
            for skill in skill_gaps[:3]
        )

        explanation += (
            f" Skills you may need to develop further "
            f"include {gap_text}."
        )

    return explanation


# ============================================================
# GENERATE SINGLE CAREER RECOMMENDATION
# ============================================================

def generate_career_recommendation(
    top_career,
    careers,
    student_skills
):
    """
    Generate detailed recommendation
    for one career.
    """

    career_name = top_career["career"]

    percentage = float(
        top_career["match_percentage"]
    )

    career_data = find_career_requirements(
        career_name,
        careers
    )

    if career_data:

        required_skills = normalize_requirements(
            career_data
        )

    else:

        required_skills = []

    matching_skills = find_matching_skills(
        student_skills,
        required_skills
    )

    skill_gaps = find_skill_gaps(
        student_skills,
        required_skills
    )

    why_career = generate_why_career(
        career_name,
        percentage,
        matching_skills,
        skill_gaps
    )

    return {
        "rank": top_career.get("rank"),
        "career": career_name,
        "match_percentage": percentage,
        "matching_skills": matching_skills,
        "skill_gaps": skill_gaps,
        "why_this_career": why_career
    }


# ============================================================
# GENERATE ALL RECOMMENDATIONS
# ============================================================

def generate_recommendations(
    top_careers,
    student_skills
):
    """
    Generate detailed recommendations
    for all Top Careers.
    """

    careers = load_career_requirements()

    recommendations = []

    for top_career in top_careers:

        recommendation = (
            generate_career_recommendation(
                top_career,
                careers,
                student_skills
            )
        )

        recommendations.append(
            recommendation
        )

    return recommendations


# ============================================================
# FINAL RESULT
# ============================================================

def generate_final_result(
    student_skills,
    recommendations
):
    """
    Generate final structured career
    recommendation result.
    """

    return {
        "student_skill_profile": {
            "skills": student_skills
        },

        "career_recommendations": {
            "total_recommendations": len(
                recommendations
            ),
            "recommendations": recommendations
        }
    }


# ============================================================
# SAVE RESULT
# ============================================================

def save_result(
    result,
    output_file=OUTPUT_FILE
):
    """
    Save final career recommendations.
    """

    output_directory = os.path.dirname(
        output_file
    )

    if output_directory:
        os.makedirs(
            output_directory,
            exist_ok=True
        )

    with open(
        output_file,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            result,
            file,
            indent=2,
            ensure_ascii=False
        )

    return output_file


# ============================================================
# TEST
# ============================================================

if __name__ == "__main__":

    print()
    print("========================================")
    print("MINERVA CAREER RECOMMENDATION TEST")
    print("========================================")

    # --------------------------------------------------------
    # Sample Student Skill Profile
    # --------------------------------------------------------

    sample_student_skills = [
        "analytical_thinking",
        "problem_solving",
        "logical_reasoning",
        "technical_aptitude",
        "learning_ability"
    ]

    # --------------------------------------------------------
    # Load Top Careers
    # --------------------------------------------------------

    top_careers = load_top_careers()

    print()
    print(
        f"Top Careers Loaded: "
        f"{len(top_careers)}"
    )

    # --------------------------------------------------------
    # Generate Recommendations
    # --------------------------------------------------------

    recommendations = generate_recommendations(
        top_careers,
        sample_student_skills
    )

    # --------------------------------------------------------
    # Generate Final Result
    # --------------------------------------------------------

    final_result = generate_final_result(
        sample_student_skills,
        recommendations
    )

    # --------------------------------------------------------
    # Display Results
    # --------------------------------------------------------

    print()
    print("Career Recommendations:")
    print("----------------------------------------")

    for recommendation in recommendations:

        print(
            f"{recommendation['rank']}. "
            f"{recommendation['career']} → "
            f"{recommendation['match_percentage']}%"
        )

        print(
            f"   Matching Skills: "
            f"{', '.join(recommendation['matching_skills'])}"
        )

        print(
            f"   Skill Gaps: "
            f"{', '.join(recommendation['skill_gaps'])}"
        )

        print(
            f"   Why: "
            f"{recommendation['why_this_career']}"
        )

        print()

    # --------------------------------------------------------
    # Save Result
    # --------------------------------------------------------

    output_file = save_result(
        final_result
    )

    print("========================================")
    print("CAREER RECOMMENDATIONS SAVED")
    print("========================================")
    print(f"File: {output_file}")