import json


# ============================================================
# FILE PATHS
# ============================================================

CAREERS_FILE = "../data/career_requirements.json"
TOP_CAREERS_FILE = "../data/top_career_matches.json"
OUTPUT_FILE = "../data/career_explanations.json"


# ============================================================
# LOAD CAREER REQUIREMENTS
# ============================================================

def load_career_requirements():
    """
    Load all career requirements from JSON.
    """

    with open(
        CAREERS_FILE,
        "r",
        encoding="utf-8"
    ) as file:

        data = json.load(file)

    return data["careers"]


# ============================================================
# LOAD TOP CAREERS
# ============================================================

def load_top_careers():
    """
    Load top career matches generated by 4.3.
    """

    with open(
        TOP_CAREERS_FILE,
        "r",
        encoding="utf-8"
    ) as file:

        data = json.load(file)

    return data["top_careers"]


# ============================================================
# FIND CAREER
# ============================================================

def find_career(
    career_name,
    careers
):
    """
    Find career information using career name.
    """

    for career in careers:

        if career["career"] == career_name:
            return career

    return None


# ============================================================
# IDENTIFY MATCHING SKILLS
# ============================================================

def identify_matching_skills(
    required_skills,
    student_skills
):
    """
    Identify skills where student's score
    meets or exceeds career requirement.
    """

    matching_skills = []

    for skill, required_level in required_skills.items():

        student_level = student_skills.get(
            skill,
            0
        )

        if student_level >= required_level:

            matching_skills.append({
                "skill": skill,
                "student_score": student_level,
                "required_score": required_level
            })

    return matching_skills


# ============================================================
# IDENTIFY SKILL GAPS
# ============================================================

def identify_skill_gaps(
    required_skills,
    student_skills
):
    """
    Identify skills that need improvement.
    """

    skill_gaps = []

    for skill, required_level in required_skills.items():

        student_level = student_skills.get(
            skill,
            0
        )

        if student_level < required_level:

            skill_gaps.append({
                "skill": skill,
                "student_score": student_level,
                "required_score": required_level,
                "gap": round(
                    required_level - student_level,
                    2
                )
            })

    return skill_gaps


# ============================================================
# GENERATE WHY CAREER EXPLANATION
# ============================================================

def generate_why_career(
    career_name,
    match_percentage,
    matching_skills,
    skill_gaps
):
    """
    Generate a natural-language explanation
    for why the career was recommended.
    """

    if matching_skills:

        skill_names = [
            item["skill"].replace("_", " ")
            for item in matching_skills
        ]

        if len(skill_names) == 1:

            matching_text = skill_names[0]

        elif len(skill_names) == 2:

            matching_text = (
                f"{skill_names[0]} and "
                f"{skill_names[1]}"
            )

        else:

            matching_text = (
                ", ".join(skill_names[:-1])
                + ", and "
                + skill_names[-1]
            )

    else:

        matching_text = "several relevant skills"

    if skill_gaps:

        gap_names = [
            item["skill"].replace("_", " ")
            for item in skill_gaps
        ]

        if len(gap_names) == 1:

            gap_text = gap_names[0]

        elif len(gap_names) == 2:

            gap_text = (
                f"{gap_names[0]} and "
                f"{gap_names[1]}"
            )

        else:

            gap_text = (
                ", ".join(gap_names[:-1])
                + ", and "
                + gap_names[-1]
            )

        explanation = (
            f"{career_name} is a {match_percentage}% "
            f"career match for you. Your assessment "
            f"profile shows good alignment with "
            f"{matching_text}. To become even more "
            f"prepared for this career, you should "
            f"focus on improving {gap_text}."
        )

    else:

        explanation = (
            f"{career_name} is a {match_percentage}% "
            f"career match for you. Your assessment "
            f"profile strongly aligns with the "
            f"required skills, including "
            f"{matching_text}. Your current skill "
            f"profile shows strong readiness for "
            f"this career."
        )

    return explanation


# ============================================================
# GENERATE CAREER EXPLANATION
# ============================================================

def generate_career_explanation(
    career,
    student_skills,
    match_percentage
):
    """
    Generate complete explanation for one career.
    """

    required_skills = career.get(
        "required_skills",
        {}
    )

    matching_skills = identify_matching_skills(
        required_skills,
        student_skills
    )

    skill_gaps = identify_skill_gaps(
        required_skills,
        student_skills
    )

    why_career = generate_why_career(
        career["career"],
        match_percentage,
        matching_skills,
        skill_gaps
    )

    return {

        "career": career["career"],

        "match_percentage": match_percentage,

        "description": career.get(
            "description",
            ""
        ),

        "matching_skills": matching_skills,

        "skill_gaps": skill_gaps,

        "why_this_career": why_career

    }


# ============================================================
# GENERATE ALL EXPLANATIONS
# ============================================================

def generate_all_explanations(
    top_careers,
    student_skills
):
    """
    Generate explanations for all top careers.
    """

    careers = load_career_requirements()

    explanations = []

    for career_match in top_careers:

        career_name = career_match["career"]

        match_percentage = career_match[
            "match_percentage"
        ]

        career = find_career(
            career_name,
            careers
        )

        if career is None:
            continue

        explanation = generate_career_explanation(
            career,
            student_skills,
            match_percentage
        )

        explanations.append(
            explanation
        )

    return explanations


# ============================================================
# SAVE RESULT
# ============================================================

def save_explanations(
    explanations
):
    """
    Save career explanations to JSON.
    """

    final_result = {

        "assessment": {
            "name": "Minerva Career Assessment",
            "version": "1.0"
        },

        "career_explanations": explanations

    }

    with open(
        OUTPUT_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            final_result,
            file,
            indent=2,
            ensure_ascii=False
        )

    print(
        f"\nCareer explanations saved: "
        f"{OUTPUT_FILE}"
    )


# ============================================================
# MAIN TEST
# ============================================================

if __name__ == "__main__":

    print("\n========================================")
    print("MINERVA CAREER EXPLANATION TEST")
    print("========================================")

    # --------------------------------------------------------
    # Load top careers
    # --------------------------------------------------------

    top_careers = load_top_careers()

    # Use top 10 careers
    top_careers = top_careers[:10]

    # --------------------------------------------------------
    # Sample student skill profile
    # --------------------------------------------------------

    sample_student_skills = {

        "problem_solving": 85,

        "analytical_thinking": 82,

        "logical_reasoning": 80,

        "technical_aptitude": 78,

        "creativity": 65,

        "communication": 60,

        "attention_to_detail": 70,

        "learning_ability": 88

    }

    # --------------------------------------------------------
    # Generate explanations
    # --------------------------------------------------------

    explanations = generate_all_explanations(
        top_careers,
        sample_student_skills
    )

    # --------------------------------------------------------
    # Display results
    # --------------------------------------------------------

    print("\nCareer Explanations:")
    print("----------------------------------------")

    for index, career in enumerate(
        explanations,
        start=1
    ):

        print(
            f"{index}. "
            f"{career['career']} "
            f"→ "
            f"{career['match_percentage']}%"
        )

        print(
            f"   Why: "
            f"{career['why_this_career']}"
        )

        print("   Matching Skills:")

        if career["matching_skills"]:

            for skill in career[
                "matching_skills"
            ]:

                print(
                    f"      - "
                    f"{skill['skill']}: "
                    f"{skill['student_score']}%"
                )

        else:

            print("      None")

        print("   Skill Gaps:")

        if career["skill_gaps"]:

            for gap in career[
                "skill_gaps"
            ]:

                print(
                    f"      - "
                    f"{gap['skill']}: "
                    f"{gap['student_score']}% "
                    f"(required "
                    f"{gap['required_score']}%)"
                )

        else:

            print("      None")

        print()

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    save_explanations(
        explanations
    )