"""
Minerva Career Intelligence
4.3 — Top Career Matches

Purpose:
    Take all career matches generated by career_matching.py,
    sort them by match percentage, select the Top 10 careers,
    and generate a simple "Why this career?" explanation.
"""

import json


# ============================================================
# CONFIGURATION
# ============================================================

TOP_N = 10


# ============================================================
# WHY THIS CAREER
# ============================================================

def generate_why_career(career, match_percentage):
    """
    Generate a basic explanation for why a career
    is recommended to the student.

    Parameters:
        career: Career name
        match_percentage: Career match percentage

    Returns:
        String explanation
    """

    if match_percentage >= 90:
        level = "very strong"
    elif match_percentage >= 80:
        level = "strong"
    elif match_percentage >= 70:
        level = "good"
    elif match_percentage >= 60:
        level = "moderate"
    else:
        level = "developing"

    return (
        f"Your assessment skill profile shows a {level} "
        f"alignment with the requirements of {career}. "
        f"The calculated career match is {match_percentage}%."
    )


# ============================================================
# NORMALIZE CAREER MATCH
# ============================================================

def normalize_match(match):
    """
    Normalize different possible career match formats.

    Expected format from career_matching.py:

    {
        "career": "Data Scientist",
        "match_percentage": 85.5
    }

    Also supports:

    {
        "career": "Data Scientist",
        "match": 85.5
    }
    """

    career_name = (
        match.get("career")
        or match.get("career_name")
        or match.get("name")
    )

    percentage = (
        match.get("match_percentage")
        if match.get("match_percentage") is not None
        else match.get("match")
    )

    if career_name is None:
        raise ValueError(
            "Career match does not contain a career name."
        )

    if percentage is None:
        raise ValueError(
            f"Match percentage missing for career: {career_name}"
        )

    return {
        "career": career_name,
        "match_percentage": round(float(percentage), 2)
    }


# ============================================================
# GET TOP CAREERS
# ============================================================

def get_top_careers(career_matches, top_n=TOP_N):
    """
    Sort all career matches by match percentage
    and return the Top N careers.

    Parameters:
        career_matches:
            List of career match dictionaries.

        top_n:
            Number of careers to return.

    Returns:
        List containing Top N careers.
    """

    if not career_matches:
        return []

    normalized_matches = []

    for match in career_matches:

        normalized = normalize_match(match)

        normalized_matches.append(normalized)

    # Sort highest match first
    normalized_matches.sort(
        key=lambda x: x["match_percentage"],
        reverse=True
    )

    # Select Top N
    top_matches = normalized_matches[:top_n]

    # Add ranking and explanation
    final_top_careers = []

    for rank, match in enumerate(
        top_matches,
        start=1
    ):

        career = match["career"]
        percentage = match["match_percentage"]

        final_top_careers.append({
            "rank": rank,
            "career": career,
            "match_percentage": percentage,
            "why_this_career": generate_why_career(
                career,
                percentage
            )
        })

    return final_top_careers


# ============================================================
# GENERATE FINAL TOP CAREER RESULT
# ============================================================

def generate_top_career_result(
    career_matches,
    top_n=TOP_N
):
    """
    Generate final structured Top Career result.

    This function is the main function that
    the backend can later call.
    """

    top_careers = get_top_careers(
        career_matches,
        top_n
    )

    return {
        "total_careers_analyzed": len(career_matches),
        "top_careers_count": len(top_careers),
        "top_careers": top_careers
    }


# ============================================================
# SAVE RESULT
# ============================================================

def save_top_careers(
    result,
    output_file="../data/top_career_matches.json"
):
    """
    Save Top Career result as JSON.
    """

    with open(
        output_file,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            result,
            file,
            indent=2,
            ensure_ascii=False
        )

    return output_file


# ============================================================
# TEST
# ============================================================

if __name__ == "__main__":

    print()
    print("========================================")
    print("MINERVA TOP CAREER MATCHES TEST")
    print("========================================")

    # --------------------------------------------------------
    # Sample output from career_matching.py
    # --------------------------------------------------------

    sample_career_matches = [

        {
            "career": "Data Engineer",
            "match_percentage": 80.74
        },

        {
            "career": "Embedded Systems Engineer",
            "match_percentage": 80.74
        },

        {
            "career": "Backend Developer",
            "match_percentage": 80.73
        },

        {
            "career": "MLOps Engineer",
            "match_percentage": 80.72
        },

        {
            "career": "Cloud Engineer",
            "match_percentage": 80.70
        },

        {
            "career": "Database Administrator",
            "match_percentage": 80.69
        },

        {
            "career": "Computer Vision Engineer",
            "match_percentage": 80.68
        },

        {
            "career": "Deep Learning Engineer",
            "match_percentage": 80.66
        },

        {
            "career": "Machine Learning Engineer",
            "match_percentage": 80.63
        },

        {
            "career": "Cybersecurity Engineer",
            "match_percentage": 80.63
        },

        {
            "career": "Site Reliability Engineer",
            "match_percentage": 80.63
        },

        {
            "career": "Database Developer",
            "match_percentage": 80.61
        },

        {
            "career": "Network Engineer",
            "match_percentage": 80.60
        },

        {
            "career": "AI Engineer",
            "match_percentage": 80.57
        },

        {
            "career": "Cybersecurity Analyst",
            "match_percentage": 80.56
        },

        {
            "career": "Software Developer",
            "match_percentage": 80.55
        },

        {
            "career": "Systems Administrator",
            "match_percentage": 80.55
        },

        {
            "career": "DevOps Engineer",
            "match_percentage": 80.53
        },

        {
            "career": "Security Engineer",
            "match_percentage": 80.52
        },

        {
            "career": "IoT Engineer",
            "match_percentage": 80.49
        },

        {
            "career": "Digital Forensics Analyst",
            "match_percentage": 80.48
        },

        {
            "career": "Android Developer",
            "match_percentage": 80.47
        },

        {
            "career": "Software Engineer",
            "match_percentage": 80.42
        },

        {
            "career": "AI Researcher",
            "match_percentage": 80.39
        },

        {
            "career": "Mobile App Developer",
            "match_percentage": 80.38
        },

        {
            "career": "iOS Developer",
            "match_percentage": 80.38
        },

        {
            "career": "Data Scientist",
            "match_percentage": 80.38
        },

        {
            "career": "Penetration Tester",
            "match_percentage": 80.36
        },

        {
            "career": "Full Stack Developer",
            "match_percentage": 80.30
        },

        {
            "career": "QA / Software Test Engineer",
            "match_percentage": 80.16
        },

        {
            "career": "Game Developer",
            "match_percentage": 80.13
        },

        {
            "career": "Data Analyst",
            "match_percentage": 80.08
        },

        {
            "career": "Web Developer",
            "match_percentage": 80.07
        },

        {
            "career": "NLP Engineer",
            "match_percentage": 80.07
        },

        {
            "career": "Frontend Developer",
            "match_percentage": 79.86
        },

        {
            "career": "IT Support Specialist",
            "match_percentage": 79.80
        },

        {
            "career": "Business Analyst (IT)",
            "match_percentage": 79.66
        },

        {
            "career": "Product Manager (Tech)",
            "match_percentage": 79.52
        },

        {
            "career": "Product Designer",
            "match_percentage": 79.14
        },

        {
            "career": "UI/UX Designer",
            "match_percentage": 79.12
        }
    ]

    # --------------------------------------------------------
    # Generate Top Careers
    # --------------------------------------------------------

    final_result = generate_top_career_result(
        sample_career_matches,
        top_n=10
    )

    # --------------------------------------------------------
    # Display Result
    # --------------------------------------------------------

    print()
    print("Top Career Matches:")
    print("----------------------------------------")

    for career in final_result["top_careers"]:

        print(
            f"{career['rank']}. "
            f"{career['career']} → "
            f"{career['match_percentage']}%"
        )

        print(
            f"   Why: "
            f"{career['why_this_career']}"
        )

    # --------------------------------------------------------
    # Save Result
    # --------------------------------------------------------

    output_file = save_top_careers(
        final_result
    )

    print()
    print("========================================")
    print("TOP CAREER RESULT SAVED")
    print("========================================")
    print(f"File: {output_file}")